before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
archives:
  - format: zip
    replacements:
      '386': i386
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    files:
      - README.md
      - LICENSE
      - example_config.yml
checksum:
  name_template: checksums.txt
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
