version: '3.9'
services:
  bot:
    image: thetipo01/yadmb
# Uncomment the following line to build the image locally
#    build: .
    restart: always
    volumes:
      - ./audio_cache:/audio_cache
      - ./data:/data
