version: '3.9'
services:
  bot:
    image: thetipo01/yadmb
    restart: always
    volumes:
      - ./audio_cache:/audio_cache
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
