version: '3.9'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.yml:/app/config.yml
      - ./audio_cache:/app/audio_cache
      - ./data:/app/data
