# Example configuration file, remember to remove "example_" from the file after adding your tokens!

# Discord Bot token:
# To get your bot's token, go to https://discord.com/developers/applications click "New application",
# click "Bot" on the left bar, click "Add bot" and confirm, then click "Copy" under "Click to reveal token"
token: ""

# Owner id
# Put here the id of the owner of the bot, so they can use commands like restart
owner: ""

# Spotify Client ID and Client Secret, to support spotify playlists:
# To get your client ID and secret you need to visit https://developer.spotify.com/dashboard/applications and log in or create a new account,
# click "Create an app", give it a name and description, check both boxes and click "Create",
# then you can find your Client ID and to find your Client Secret simply click "Show Client Secret"
clientid: ""
clientsecret: ""

# YouTube API key, to parse YouTube information faster.
# It's not required, but it's recommended.
# You can get your API key by:
# - creating a new project at https://console.developers.google.com/apis/dashboard
# - clicking "Enable APIs and Services", searching for "YouTube Data API v3", clicking "Enable",
# - clicking "Credentials" on the left bar, then "Create Credentials", then "API key"
youtubeapikey: ""


# DON'T TOUCH THIS IF YOU DON'T KNOW WHAT YOU ARE DOING:
# DB Info, like username, password...
# SQLite
datasourcename: ./data/yadmb.db
# MySQL
#datasourcename: user:pass@tcp(ip:3306)/database

# Driver type, aka what database to use.
# For now, we support only "sqlite" and "mysql"
# SQLite
drivername: sqlite
# MySQL
#drivername: mysql

# Log level. Possible value are error, warning, informational and debug
loglevel: informational

# Web server address, to access the web interface
address: :8080

# Long-lived API tokens, to access the API without having to log in every time.
#apitokens:
#  - userid: 0000000000000000
#    token: correct-horse-battery-staple
#    guildid: 0000000000000000
#    textchannelid: 0000000000000000
#  - userid: 1111111111111111
#    token: correct-horse-battery-staple
#    guildid: 0000000000000000
#    textchannelid: 0000000000000000