#Example configuration file, remember to remove "example_" from the file after adding your tokens!
#For getting a discord token: https://discord.com/developers/applications
#For getting client id and secret from spotify: https://developer.spotify.com/dashboard/applications

#Bot token
token: 
#Prefix for bot commands (Note: this line is bugged, if you want to change the prefix start the program with the parameter "-prefix <your prefix>" )
prefix:
#Spotify client id, for playlist support
clientid: 
#Spotify client secret, for playlist support
clientsecret:
#DB Info, like username, password...
datasourcename: user:pass@tcp(ip:3306)/database
#Driver type, aka what database to use. For now we support only sqlite3 and mysql
drivername: mysql