site_name: YADMB
theme:
  name: material

site_description: Yet Another Discord Music Bot - A music bot written in go

# Repository
repo_name: TheTipo01/YADMB
repo_url: https://github.com/TheTipo01/YADMB
