site_name: YADMB
site_description: Yet Another Discord Music Bot - A music bot written in go

theme:
  name: material
plugins:
  - render_swagger

# Repository
repo_name: TheTipo01/YADMB
repo_url: https://github.com/TheTipo01/YADMB
