site_name: YADMB
site_description: Yet Another Discord Music Bot - A music bot written in go

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.path
plugins:
  - render_swagger
  - search

# Repository
repo_name: TheTipo01/YADMB
repo_url: https://github.com/TheTipo01/YADMB
