site_name: YADMB
site_description: Yet Another Discord Music Bot - A music bot written in go

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.path
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - render_swagger
  - search
  - offline

# Repository
repo_name: TheTipo01/YADMB
repo_url: https://github.com/TheTipo01/YADMB
