name: goreleaser
permissions:
  contents: write

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 26 ]
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: 11
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: web/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: web
      - name: Build the website
        run: pnpm run build
        working-directory: web
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: 'stable'
          cache: true
          cache-dependency-path: go.sum
      - name: Download and run libdave installation script
        env:
          SHELL: /bin/sh
        run: |
          wget https://raw.githubusercontent.com/disgoorg/godave/5e485dc29cde1d4664282fe2f47c841e032833b3/scripts/libdave_install.sh
          chmod +x libdave_install.sh
          ./libdave_install.sh v1.1.0
          rm libdave_install.sh
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_CONFIG_PATH: /home/runner/.local/lib/pkgconfig
